name: marcelsouza
favicon: null
layout_spectrum: 0.24120768159627914
typography_spectrum: 0.7718642649706453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5324098279234022
  lightness: 0.5586554550100118
  saturation: 0.6922596415970474
  rhythmicContrast: 0.33976003690622747
purpose: []
